### ISSUE TITLE
need to store full response object instead

### ISSUE THREAD

**Issue by bertsky** [sounding-spirit/google-ocr-testbed#1]
https://github.com/sounding-spirit/google-ocr-testbed/blob/bb6e5e42caba88b36bd1865a3bd4d5dd87b69da2/gcv_words.py#L22-L23

IIUC you need to store the full response object (JSON), not just the `full_text_annotation` part.

Format converters like [PRImA PAGE converter](https://github.com/PRImA-Research-Lab/prima-core-libs/blob/1bdcc5720d8805b431196c373bcc36633776dfee/java/PrimaDla/src/org/primaresearch/dla/page/io/json/GoogleJsonPageReader.java#L90-L91) or [gcv2hocr](https://github.com/dinosauria123/gcv2hocr) expect the full response.

**Comment by wrznr** [comment]
@bertsky This could actually be the/one reason why the conversion fails.

@sarepal So no TOML ;). Could you rerun the OCR and add the full response (JSON) to the repo?

**Comment by sarepal** [comment]
@bertsky @wrznr The response objects serialized to JSON are now in the repo.

**Comment by bertsky** [comment]
thx @sarepal – that's better, but it appears we still need the outer `{ "responses": [ ... ] }` part. I'll prepare a PR for the changes and the PAGE results.
